version: '3.8'

services:
# Nginx Service for the second instance
  nginx_stag:
    image: nginx:alpine
    container_name: zora_laravel_nginx_stag
    restart: unless-stopped
    ports:
      - "80:80"  # Second instance on port 8081
    volumes:
      - ./laravel-dashboard/:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network_stag
    depends_on:
      - php_stag

  # PHP-FPM Service for the second instance
  php_stag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zora_laravel_php_stag
    restart: unless-stopped
    volumes:
      - ./laravel-dashboard:/var/www/html
    networks:
      - laravel_network_stag

  # Server OCPP
  ocpp_server_stag:
    build:
      context: ./ocpp-server
      dockerfile: Dockerfile
    container_name: zora_ocpp_stag
    restart: unless-stopped
    env_file:
      - ./ocpp-env/.env
    ports:
      - "9001:9001"
    networks:
      - laravel_network_stag

networks:
  laravel_network_stag:
    driver: bridge
